### ISSUE TITLE
Remove support for escaped-colon syntax in favor of using ${} for formatting in the future

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/StyledStrings.jl#28]
I'm thinking it could be worth reverting 5dd8b9e6fd02287305f1f122e8f084ffcb7266fe considering the annoyances with requiring `:` to be escaped laid out in #1, and that this change would be annoying to make in a backwards-compatible way past the initial release (currently `${}` is a syntax error, so it can be introduced in the future as a non-breaking change).

I'd like to get other people's thoughts on this, but if there aren't any comments against the change within the next fortnight or so I'll just do it.

**Comment by jariji** [comment]
Too late now, I'll just mention I think Swift's `"foo \(bar) baz"` would probably have been a better syntax than `$` for Julia string escape. Since `\` is already special syntax we don't lose anything, whereas `$` is otherwise valid in a string.

**Comment by tecosaur** [comment]
Yea, I personally prefer `\(interpolate)` too but I think that ship has already sailed.
