### ISSUE TITLE
Register StyledStrings.jl 1.0 in general

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/StyledStrings.jl#5]
As of JuliaLang/julia#49586 we have the StyledStrings stdlib. Thanks to it being an external stlib, we can also register it in General.

I think we can be a bit sneakier though, and do the following:
- Overhaul parts of the codebase to make it Julia 1.0 compatible (I already have most of this work saved)
- Register this as version `1.0` in general
- Revert that overhaul
- Register version `1.11` in general
- Profit (backwards compatibility)

I think we want to do this just before 1.11, so the registered 1.0 version behaves as near-identically as possible. This issue is mainly to serve as a tracked reminder for me to do so.

**Comment by tecosaur** [comment]
Support for 1.0 is now a work in progress over at https://github.com/julialang/StyledStrings.jl/tree/julia1-compat

**Comment by zsz00** [comment]
Hope to register this package ASAP  @tecosaur

**Comment by tecosaur** [comment]
The current plan is to register this around the Julia 1.11 release, so that 1.0 can be as "up to date" as possible, since past that release my plan is to only push bugfixes to pre-1.11.

**Comment by tecosaur** [comment]
> Why wait for v1.0 (or v1.11) in the first place?

I see it as rather important that the compat-registered version of StyledStrings mirrors the version in 1.11 as closely as possible.

Rather crucially, the compat version also needs to vendor the new AnnotatedString functionality from Base.

Currently there are three changes that I'm trying to get reviewed and merged for 1.11:
- https://github.com/JuliaLang/julia/pull/53715, I think this functionality is rather important, but I don't like the form that my current best idea of implementing it takes. Reviews/suggestions here would be appreciated.
- https://github.com/JuliaLang/julia/pull/54289, resulting from a long chat I had with Lilith last week. I anticipate this should be merged soon.
- [immanent PR](https://github.com/JuliaLang/julia/compare/master...tecosaur:julia:annot-substring-compison) as per https://github.com/JuliaLang/julia/issues/53042#issuecomment-2080982369, which should also be a quick merge once the PR is made (within the next day or few).

> Julia v1.11.0 is already in the beta testing phase, but the (weak) dependent packages are in trouble with testing.

I do sympathise with this, I'm just not sure if quickly releasing something so that package management is happy is the right approach?

Perhaps I'm just slightly caught by the sunk cost fallacy, but it feels to me that the code that will be in 1.11 is so very close to ironed down that it might be best to wait the _just a little longer_ :crossed_fingers: to be able to register the "fully mirrors the functionality in 1.11" version.

**Comment by kimikage** [comment]
It is up to the package to determine if the incomplete `StyledStrings` are compatible with the package, so it should not matter how compatible it is with v1.11.
However, the problem is at the stage of installing packages.

In any case, you are the one who knows best about this library. So, v0.x registration probably should not take place.

**Comment by tecosaur** [comment]
This process has been dragging on a bit. I'll tell you what, I'll see if I can't get the items I listed sorted within a week or so, and then make the aforementioned 1.0 release.

If not I'm willing to re-evaluate the idea of a pre-release just so weakdeps are resolvable.

**Comment by tecosaur** [comment]
Update: we're reaching the end of the week and ... it's all been merged!

Now I just need to backport/grab the changes, make sure all the tests still pass on older version, and then we'll have the compat release I've been talking along for so long :grinning:

**Comment by tecosaur** [comment]
The compat version is about to be registered :slightly_smiling_face: 
- https://github.com/JuliaRegistries/General/pull/106027
