### ISSUE TITLE
Don't assume `DEPOT_PATH` is populated

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/StyledStrings.jl#58]
https://github.com/JuliaLang/StyledStrings.jl/blob/d7496d24d3f05536bce6a7eb4cd8ca05a75c02aa/src/StyledStrings.jl#L21

will error on empty `DEPOT_PATH`

**Comment by tecosaur** [comment]
Ah, interesting. I assumed the `DEPOT_PATH` is always populated. Just not doing anything when this is the case seems like an obvious fix, but I'd be interested to know when this situation occurs.

**Comment by KristofferC** [comment]
You can set the depot path with an env variable (and set it to be empty).

**Comment by tecosaur** [comment]
Ah right thanks, I'll just apply the change Jeff suggests and do nothing when that's the case then.

**Comment by tecosaur** [comment]
Closed by #59.
