### ISSUE TITLE
Bug in src/regioniterator.jl

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/StyledStrings.jl#8]
https://github.com/JuliaLang/StyledStrings.jl/blob/74e7135ef86ef50a62f19956c7a5f824c391389e/src/regioniterator.jl#L30

`import AnnotatedString` does not make sense. I think this would get caught in CI if it built docs.

**Comment by tecosaur** [comment]
Hmm, this might be caught if the docs could actually build themselves.
